#!/usr/bin/env python3
"""
Judge Model Agent

This script evaluates agent-generated responses using various judge models.
It loads per-PID prompts from CSV or applies one shared prompt to discovered
workspace directories, then evaluates each final workspace.
"""

import argparse
import json
import os
from typing import Any

import pandas as pd

from judge_util import (
    JudgeModelManager, 
    EvaluationStandard, 
    save_results_to_json
)


class WorkspaceResponseReader:
    """Handles reading and processing workspace directories generated by agents."""
    
    def __init__(self, max_file_size_mb: int = 10):
        self.max_file_size_mb = max_file_size_mb
        self.max_size_bytes = max_file_size_mb * 1024 * 1024
        
        # Git-related files and directories to exclude
        self.git_exclusions = {
            '.git',           # Git directory
            '.gitignore',     # Git ignore file
            '.gitattributes', # Git attributes file
            '.gitmodules',    # Git submodules file
            '.gitkeep',       # Git keep file
            '.github',        # GitHub workflows and configs
        }
    
    def get_directory_tree(self, directory: str, prefix: str = "", is_last: bool = True) -> str:
        """Generate a visual tree representation of the directory structure."""
        if not os.path.exists(directory):
            return "Directory not found"
        
        tree_lines = []
        base_name = os.path.basename(directory) or directory
        tree_lines.append(f"{prefix}{'└── ' if is_last else '├── '}{base_name}/")
        
        # Get all items (files and directories) in the current directory
        try:
            items = os.listdir(directory)
        except PermissionError:
            tree_lines.append(f"{prefix}    [Permission Denied]")
            return "\n".join(tree_lines)
        
        # Filter out git-related items
        items = [item for item in items if item not in self.git_exclusions]
        
        # Separate and sort directories and files
        dirs = sorted([item for item in items if os.path.isdir(os.path.join(directory, item))])
        files = sorted([item for item in items if os.path.isfile(os.path.join(directory, item))])
        
        # Combine them (directories first, then files)
        all_items = dirs + files
        
        for i, item in enumerate(all_items):
            item_path = os.path.join(directory, item)
            is_last_item = i == len(all_items) - 1
            
            if os.path.isdir(item_path):
                # Recursively process subdirectories
                new_prefix = prefix + ("    " if is_last else "│   ")
                subtree = self.get_directory_tree(item_path, new_prefix, is_last_item)
                # Skip the first line (directory name) since we'll add it ourselves
                subtree_lines = subtree.split('\n')[1:]
                tree_lines.append(f"{prefix}{'└── ' if is_last_item else '├── '}{item}/")
                tree_lines.extend(subtree_lines)
            else:
                # Add files
                tree_lines.append(f"{prefix}{'└── ' if is_last_item else '├── '}{item}")
        
        return "\n".join(tree_lines)
    
    def read_workspace_response(self, directory: str) -> str:
        """
        Read all files in a workspace directory and return as structured JSON string.
        
        Args:
            directory: Path to the workspace directory
            
        Returns:
            JSON string containing directory tree, file contents, and summary
        """
        # Generate directory tree
        tree_structure = self.get_directory_tree(directory)
        directory_id = directory.split("/")[-1]
        tree_structure = tree_structure.replace(directory_id + "/", "workspace/")
        
        # Read all files
        response_dict = {}
        skipped_files = []
        
        for root, dirs, files in os.walk(directory):
            # Filter out git-related directories from dirs list (modifies in-place to prevent os.walk from entering them)
            dirs[:] = [d for d in dirs if d not in self.git_exclusions]
            
            # Filter out git-related files
            files = [f for f in files if f not in self.git_exclusions]
            
            for file in files:
                file_path = os.path.join(root, file)
                relative_path = os.path.relpath(file_path, directory)
                
                # Skip if any part of the path contains git-related items
                path_parts = relative_path.split(os.sep)
                if any(part in self.git_exclusions for part in path_parts):
                    continue
                
                try:
                    # Check file size first
                    file_size = os.path.getsize(file_path)
                    
                    if file_size > self.max_size_bytes:
                        size_mb = file_size / (1024 * 1024)
                        skipped_files.append({
                            "path": relative_path,
                            "size_mb": round(size_mb, 2),
                            "reason": f"File too large ({size_mb:.2f}MB > {self.max_file_size_mb}MB)"
                        })
                        print(f"Skipping large file {relative_path}: {size_mb:.2f}MB")
                        continue
                    
                    # Read the file if it's within size limit
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        response_dict[relative_path] = content
                        
                except Exception as e:
                    print(f"Error reading file {file_path}: {e}")
                    skipped_files.append({
                        "path": relative_path,
                        "reason": f"Error: {str(e)}"
                    })
                    continue
        
        # Create final response with tree structure, file contents, and skipped files info
        final_response = {
            "directory_tree": tree_structure,
            "files": response_dict,
            "summary": {
                "total_files_read": len(response_dict),
                "files_skipped": len(skipped_files),
                "max_file_size_mb": self.max_file_size_mb
            }
        }
        
        # Add skipped files info if any files were skipped
        if skipped_files:
            final_response["skipped_files"] = skipped_files
        
        return json.dumps(final_response, indent=4, ensure_ascii=False)


def parse_arguments():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Evaluate agent-generated responses using judge models",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
            Examples:
            %(prog)s --csv data.csv --workspace-dir ./workspaces/ --output results.json
            %(prog)s --prompt "Complete the code at <FILL_HERE>." --workspace-dir ./workspaces/ --output results.json --standard CODE_COMPLETION
            %(prog)s --csv data.csv --workspace-dir ./workspaces/ --judge-model gpt4 --standard TEXT_TO_CODE
            %(prog)s --csv data.csv --workspace-dir ./workspaces/ --max-file-size 20 --no-reasoning
            %(prog)s --csv data.csv --workspace-dir ./workspaces/ --use-litellm --judge-model claude-3-5-sonnet-20241022
            %(prog)s --csv data.csv --workspace-dir ./workspaces/ --use-litellm --judge-model ollama/llama2 --litellm-api-base http://localhost:11434
        """
    )
    
    # JAWS-0 has a different prompt for every PID, while JAWS-1 and JAWS-M
    # share one prompt across all workspaces. Keep both forms as first-class
    # input modes instead of requiring generated, repetitive CSV files.
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument(
        "--csv", "--prompt-csv",
        dest="prompt_csv_path",
        help="Path to a CSV file containing pid and prompt columns (JAWS-0)"
    )

    input_group.add_argument(
        "--prompt", "--shared-prompt",
        dest="shared_prompt",
        help=(
            "Prompt shared by every numeric PID workspace under --workspace-dir "
            "(JAWS-1 and JAWS-M)"
        )
    )
    
    parser.add_argument(
        "--workspace-dir", "--workspace-base-dir",
        dest="workspace_base_dir",
        required=True,
        help="Base directory containing workspace subdirectories"
    )

    parser.add_argument(
        "--profile-name",
        dest="profile_name",
        default="default",
        help="Profile name for the aws profile (default: default)"
    )
    
    parser.add_argument(
        "--output", "--output-file",
        dest="output_file",
        required=True,
        help="Path for output JSON file with evaluation results"
    )
    
    # Optional arguments
    parser.add_argument(
        "--judge-model", "--model",
        dest="judge_model_id",
        default="o3",
        help="Judge model ID to use for evaluation (default: o3)"
    )
    
    parser.add_argument(
        "--use-litellm",
        dest="use_litellm",
        action="store_true",
        help="Use LiteLLM for model access (enables access to 100+ providers)"
    )
    
    parser.add_argument(
        "--litellm-api-base",
        dest="litellm_api_base",
        help="Custom API base URL for LiteLLM (e.g., for local models)"
    )
    
    parser.add_argument(
        "--litellm-api-key",
        dest="litellm_api_key",
        help="API key for LiteLLM (if different from environment variables)"
    )
    
    parser.add_argument(
        "--standard", "--eval-standard",
        dest="standard",
        default="TEXT_TO_CODE",
        choices=["TEXT_TO_CODE", "CODE_COMPLETION", "CODE_TRANSLATION", "REFUSAL"],
        help="Evaluation standard to use (default: TEXT_TO_CODE)"
    )
    
    parser.add_argument(
        "--max-file-size",
        dest="max_file_size_mb",
        type=int,
        default=10,
        help="Maximum file size in MB to read (default: 10)"
    )
    
    parser.add_argument(
        "--reasoning", "--use-reasoning",
        dest="use_reasoning",
        action="store_true",
        default=True,
        help="Enable reasoning in evaluation (default: True)"
    )
    
    parser.add_argument(
        "--no-reasoning",
        dest="use_reasoning",
        action="store_false",
        help="Disable reasoning in evaluation"
    )
    
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose output"
    )
    
    return parser.parse_args()


def get_evaluation_standard(standard_name: str) -> EvaluationStandard:
    """Convert string to EvaluationStandard enum."""
    standard_mapping = {
        "TEXT_TO_CODE": EvaluationStandard.TEXT_TO_CODE,
        "CODE_COMPLETION": EvaluationStandard.CODE_COMPLETION,
        "CODE_TRANSLATION": EvaluationStandard.CODE_TRANSLATION,
        "REFUSAL": EvaluationStandard.REFUSAL
    }
    
    return standard_mapping.get(standard_name.upper(), EvaluationStandard.TEXT_TO_CODE)


def validate_arguments(args):
    """Validate command line arguments."""
    errors = []
    
    # Check the selected prompt source.
    if args.prompt_csv_path and not os.path.isfile(args.prompt_csv_path):
        errors.append(f"CSV file not found: {args.prompt_csv_path}")
    if args.shared_prompt is not None and not args.shared_prompt.strip():
        errors.append("Shared prompt must not be empty")
    
    # Check if workspace base directory exists
    if not os.path.isdir(args.workspace_base_dir):
        errors.append(f"Workspace base directory not found: {args.workspace_base_dir}")
    
    # Check if output directory is writable
    output_dir = os.path.dirname(args.output_file)
    if output_dir and not os.path.exists(output_dir):
        errors.append(f"Output directory does not exist: {output_dir}")
    elif output_dir and not os.access(output_dir, os.W_OK):
        errors.append(f"Output directory is not writable: {output_dir}")
    
    # Validate max file size
    if args.max_file_size_mb <= 0:
        errors.append("Maximum file size must be greater than 0")
    
    if errors:
        print("Validation errors:")
        for error in errors:
            print(f"  - {error}")
        return False
    
    return True


def normalize_pid(value: Any) -> str:
    """Return a stable string PID suitable for workspace paths and JSON."""
    if pd.isna(value):
        return ""

    # Pandas can represent an integer PID as a float when a CSV contains
    # missing values elsewhere in the column. Avoid producing paths like
    # workspace/183.0 in that case.
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value).strip()


def load_csv_inputs(prompt_csv_path: str) -> list[dict[str, str]]:
    """Load per-PID prompts used by JAWS-0."""
    df = pd.read_csv(prompt_csv_path)
    if df.empty:
        raise ValueError("CSV file is empty")

    missing_columns = {"pid", "prompt"} - set(df.columns)
    if missing_columns:
        missing = ", ".join(sorted(missing_columns))
        raise ValueError(f"CSV file is missing required column(s): {missing}")

    inputs = []
    for index, row in df.iterrows():
        pid = normalize_pid(row.get("pid"))
        prompt_value = row.get("prompt")
        prompt = "" if pd.isna(prompt_value) else str(prompt_value).strip()
        if not pid or not prompt:
            print(f"ERROR: Missing PID or prompt in CSV row {index}; skipping")
            continue
        inputs.append({"pid": pid, "prompt": prompt})
    return inputs


def discover_workspace_inputs(
    workspace_base_dir: str, shared_prompt: str
) -> list[dict[str, str]]:
    """Discover numeric PID directories for JAWS-1 and JAWS-M."""
    inputs = []
    for entry in os.scandir(workspace_base_dir):
        if not entry.is_dir() or not entry.name.isdigit():
            continue
        inputs.append({"pid": entry.name, "prompt": shared_prompt.strip()})

    inputs.sort(key=lambda item: int(item["pid"]))
    return inputs


def load_evaluation_inputs(args) -> list[dict[str, str]]:
    """Load the common PID/prompt representation for either input mode."""
    if args.prompt_csv_path:
        return load_csv_inputs(args.prompt_csv_path)
    return discover_workspace_inputs(args.workspace_base_dir, args.shared_prompt)


def main():
    """Main function to run agent model evaluation."""
    # Parse command line arguments
    args = parse_arguments()
    
    # Validate arguments
    if not validate_arguments(args):
        return 1
    
    # Print configuration if verbose
    if args.verbose:
        print("Configuration:")
        if args.prompt_csv_path:
            print(f"  Input mode: CSV")
            print(f"  CSV file: {args.prompt_csv_path}")
        else:
            print(f"  Input mode: shared prompt")
            print(f"  Shared prompt: {args.shared_prompt}")
        print(f"  Workspace directory: {args.workspace_base_dir}")
        print(f"  Profile name: {args.profile_name}")
        print(f"  Judge model: {args.judge_model_id}")
        print(f"  Use LiteLLM: {args.use_litellm}")
        if args.use_litellm:
            print(f"  LiteLLM API base: {args.litellm_api_base or 'Default'}")
            print(f"  LiteLLM API key: {'Set' if args.litellm_api_key else 'Not set'}")
        print(f"  Evaluation standard: {args.standard}")
        print(f"  Output file: {args.output_file}")
        print(f"  Max file size: {args.max_file_size_mb}MB")
        print(f"  Use reasoning: {args.use_reasoning}")
        print()
    
    # Load PID/prompt inputs. JAWS-0 uses per-row CSV prompts; JAWS-1 and
    # JAWS-M discover numeric workspace directories and use one shared prompt.
    try:
        evaluation_inputs = load_evaluation_inputs(args)
        if not evaluation_inputs:
            raise ValueError("No evaluable PID inputs were found")
        source = args.prompt_csv_path or args.workspace_base_dir
        print(f"Loaded {len(evaluation_inputs)} evaluation inputs from {source}")
    except Exception as e:
        print(f"Error loading evaluation inputs: {e}")
        return 1
    
    # Initialize workspace reader and judge model manager
    workspace_reader = WorkspaceResponseReader(args.max_file_size_mb)
    
    try:
        judge_manager = JudgeModelManager(
            model_id=args.judge_model_id, 
            profile_name=args.profile_name, 
            is_agent_model=True,
            use_litellm=args.use_litellm,
            litellm_api_base=args.litellm_api_base,
            litellm_api_key=args.litellm_api_key
        )
        provider_info = "LiteLLM" if args.use_litellm else "default provider"
        print(f"Initialized judge model: {args.judge_model_id} using {provider_info}")
    except Exception as e:
        print(f"Error initializing judge model: {e}")
        return 1
    
    # Process each prompt and its corresponding workspace
    evaluation_data = []
    
    for item in evaluation_inputs:
        pid = item["pid"]
        prompt = item["prompt"]
        
        # Read workspace response
        workspace_dir = os.path.join(args.workspace_base_dir, str(pid))
        
        if not os.path.exists(workspace_dir):
            print(f"ERROR: Workspace directory not found: {workspace_dir}")
            continue
        
        try:
            response = workspace_reader.read_workspace_response(workspace_dir)
        except Exception as e:
            print(f"ERROR: Failed to read workspace {workspace_dir}: {e}")
            continue
        
        evaluation_data.append({
            "pid": pid,
            "prompt": prompt,
            "response": response
        })
    
    # Convert evaluation standard
    evaluation_standard = get_evaluation_standard(args.standard)
    
    # Evaluate responses using the judge model
    try:
        results = judge_manager.batch_evaluate(
            data=evaluation_data,
            standard=evaluation_standard,
            use_reasoning=args.use_reasoning
        )
    except Exception as e:
        print(f"Error during evaluation: {e}")
        return 1
    
    # Save results to JSON file
    try:
        save_results_to_json(results, args.output_file)
        print(f"Results saved to {args.output_file}")
    except Exception as e:
        print(f"Error saving results: {e}")
        return 1
    
    return 0


if __name__ == "__main__":
    print("Running agent model evaluation...")
    exit_code = main()
    if exit_code == 0:
        print("Evaluation completed successfully.")
    else:
        print("Evaluation failed.")
    exit(exit_code)
